server:
  port: 8081
spring:
  application:
    name: farm-trace
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/farm_trace?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
#    password: 767663000
    password: 123456


mybatis-plus:
  type-aliases-package: com.ling.entity # 别名扫描包
farm:
  path: D:\farm\img\
#    path: /root/SpringBoot/files/




